import { Metadata } from "next";
import Layout from "@/components/layout/Layout";
import ContactForm from "@/components/ui/ContactForm";
import Breadcrumb from "@/components/ui/Breadcrumb";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Privacy Policy - TEAS Gurus",
  description:
    "Read our privacy policy to understand how we collect, use, and protect your personal information when you use our TEAS exam services.",
  keywords:
    "privacy policy, TEAS exam privacy, data protection, personal information, privacy terms",
  openGraph: {
    title: "Privacy Policy - TEAS Gurus",
    description:
      "Read our privacy policy to understand how we collect, use, and protect your personal information.",
    url: "https://teasgurus.com/privacy-policy",
  },
  alternates: {
    canonical: "/privacy-policy",
  },
};

export default function PrivacyPolicyPage() {
  return (
    <Layout>
      {/* Hero Section */}
      <section className="gradient-bg text-white py-20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          {/* Breadcrumb */}
          <div className="mb-8">
            <Breadcrumb />
          </div>

          <div className="text-center">
            <div className="inline-flex items-center px-4 py-2 bg-blue-100 text-blue-800 rounded-full text-sm font-semibold mb-6">
              <span className="w-2 h-2 bg-blue-600 rounded-full mr-2"></span>
              We are Teas Gurus
            </div>
            <h1 className="text-5xl md:text-6xl font-bold mb-6">
              Privacy Policy
            </h1>
            <p className="text-xl md:text-2xl mb-8 max-w-4xl mx-auto leading-relaxed">
              Learn how we collect, use, and protect your personal information
              when you use our TEAS exam services.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Link
                href="/contact"
                className="bg-yellow-500 text-gray-900 px-8 py-4 rounded-lg text-lg font-semibold hover:bg-yellow-400 transition-colors"
              >
                Contact Us
              </Link>
              <Link
                href="/terms-and-conditions"
                className="border-2 border-white text-white px-8 py-4 rounded-lg text-lg font-semibold hover:bg-white hover:text-blue-600 transition-colors"
              >
                View Terms and Conditions
              </Link>
            </div>
          </div>
        </div>
      </section>

      {/* Privacy Policy Content */}
      <section className="py-20">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="prose prose-lg max-w-none">
            <h2 className="text-3xl font-bold text-gray-900 mb-6">
              Privacy Notice
            </h2>
            <p className="text-gray-600 mb-6 leading-relaxed">
              The following privacy notice explains our policy regarding the
              personal information we collect about you in the process of your
              cooperation with Take My Online Course website. It applies to the
              information we collect about:
            </p>
            <ul className="list-disc pl-6 mb-6 text-gray-600 space-y-2">
              <li>Visitors of our website</li>
              <li>People who use our services</li>
            </ul>
            <h3 className="text-2xl font-bold text-gray-900 mb-4">
              Information we collect as you webrowse our website
            </h3>
            <p className="text-gray-600 mb-6 leading-relaxed">
              Our web server automatically collects standard information,
              including your browser type, operating system and access time. We
              collect this information in a way, which does not identify anyone.
              We do not make any attempt to find out the identities of those
              visiting our website.
            </p>
            <p className="text-gray-600 mb-6 leading-relaxed">
              This information is used only to improve the content of our web
              pages and to customize it and/or the layout of our pages. We never
              sell, rent or share any of the information we collect by this
              method (except anonymous aggregate information) with any third
              parties.
            </p>
            <p className="text-gray-600 mb-6 leading-relaxed">
              We use Google Analytics to help analyze use of our website. This
              analytical tool uses 'cookies', which are text files placed on
              your computer, to collect standard Internet log information and
              visitor behavior information in an anonymous form. The data
              generated by the cookie about your use of the website is
              transmitted to Google. This information is then used to evaluate
              visitors' use of the website and to compile statistical reports on
              website's activity. To find out more about cookies, including how
              to control and delete them, visit
            </p>
            <h3 className="text-2xl font-bold text-gray-900 mb-4">
              Information we collect when you use our services
            </h3>
            <p className="text-gray-600 mb-6 leading-relaxed">
              When you start your cooperation with us, you will be asked to
              provide personal information in order to perform payments for our
              services, control the process of your order fulfillment and
              receive the completed piece of writing. We may use any contact
              information (emails and phone numbers) submitted to this website.
              We have to hold the details of the people who have requested the
              service in order to provide it. However, we only use these details
              to provide the service the person has requested and for other
              closely related purposes. We will use your email address to send
              you notifications considering the most important stages of order
              fulfillment, such as clarification of any issues, unread messages
              and order completion. Your email and telephone number may also be
              used for promotional and marketing purposes, to notify you of
              special offers and discounts, etc.
            </p>
            <p className="text-gray-600 mb-6 leading-relaxed">
              This information will be used only by our Customer Support
              Representatives and will not on any condition be disclosed to any
              third party; it is never sold, rented or shared.
            </p>
            <p className="text-gray-600 mb-6 leading-relaxed">
              All the information in the order, inquiry pages and personal
              control panel is processed with the use of the SSL-certificate,
              which guarantees complete confidentiality and safety of all the
              transactions.
            </p>
            <h3 className="text-2xl font-bold text-gray-900 mb-4">
              Complaints or queries
            </h3>
            <p className="text-gray-600 mb-6 leading-relaxed">
              We try to meet the highest standards when collecting and using
              personal information. For this reason, we take any complaints we
              receive about this very seriously. We encourage people to bring it
              to our attention if they think that our collection or use of
              information is unfair, misleading or inappropriate. We would also
              welcome any suggestions for improving our procedures.
            </p>
            <p className="text-gray-600 mb-6 leading-relaxed">
              This privacy notice was drafted with brevity and clarity in mind.
              It does not provide exhaustive details of all the aspects of our
              collection and use of personal information. However, we are happy
              to provide any additional information or explanation needed. Any
              requests for this should be sent to our email.
            </p>
            <h3 className="text-2xl font-bold text-gray-900 mb-4">
              Access to personal information
            </h3>
            <p className="text-gray-600 mb-6 leading-relaxed">
              We try to be as open as we can in terms of giving people access to
              their personal information. Individuals can find out if we hold
              any personal information about them by making a "subject access
              request" under the Data Protection Act 1998. If we do hold
              information about you, we will:
            </p>
            <ul className="list-disc pl-6 mb-6 text-gray-600 space-y-2">
              <li>Give you a description of it;</li>
              <li>Tell you why we are holding it;</li>
              <li>Tell you to whom it could be disclosed;</li>
              <li>
                Let you have a copy of the information in an intelligible form.
              </li>
            </ul>
            <p className="text-gray-600 mb-6 leading-relaxed">
              To make a request to us for any personal information we may need
              you to put the request in writing addressing it to our Customer
              Support Representatives via email. If you agree, we will try to
              deal with your request informally, for example by providing you
              with the specific information you need over the telephone. If we
              do hold information about you, you can ask us to correct any *
              mistakes by, once again, contacting Customer Support
              Representatives.
            </p>
            <h3 className="text-2xl font-bold text-gray-900 mb-4">
              Links Disclaimer
            </h3>
            <p className="text-gray-600 mb-6 leading-relaxed">
              In order to provide visitors with certain information, this
              website provides links to local, state and federal government
              agencies, and websites of other organizations. A link does not
              constitute an endorsement of the content, viewpoint, accuracy,
              opinions, policies, products, services, or accessibility of that
              website. Once you link to another site from this website,
              including one maintained by the State, you are subject to the
              terms and conditions of that website, including, but not limited
              to, its privacy policy.
            </p>
            <div className="bg-blue-50 rounded-lg p-6 mt-8">
              <p className="text-blue-800 font-semibold mb-2">Last Updated:</p>
              <p className="text-blue-700">January 1, 2025</p>
            </div>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="bg-gradient-to-r from-blue-600 to-blue-700 rounded-2xl p-12 text-white shadow-2xl">
            <div className="max-w-3xl mx-auto text-center">
              <h2 className="text-3xl font-bold mb-4">
                Questions About Our Privacy Policy?
              </h2>
              <p className="text-xl mb-8 opacity-90 leading-relaxed">
                We're committed to transparency and protecting your privacy.
                Contact us if you have any questions about how we handle your
                information.
              </p>
              <div className="flex flex-col sm:flex-row gap-4 justify-center">
                <Link
                  href="/contact"
                  className="bg-yellow-500 text-gray-900 px-8 py-4 rounded-lg text-lg font-semibold hover:bg-yellow-400 transition-colors"
                >
                  Contact Us
                </Link>
                <Link
                  href="/terms-and-conditions"
                  className="border-2 border-white text-white px-8 py-4 rounded-lg text-lg font-semibold hover:bg-white hover:text-blue-600 transition-all duration-200 shadow-lg hover:shadow-xl transform hover:scale-105"
                >
                  View Terms and Conditions
                </Link>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Contact Form Section */}
      <section className="py-20 bg-gray-50">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12">
            <h2 className="text-4xl font-bold text-gray-900 mb-4">
              Need More Information?
            </h2>
            <p className="text-xl text-gray-600">
              Our team is here to help you understand our privacy practices and
              answer any questions you may have.
            </p>
          </div>
          <ContactForm title="Get in Touch" />
        </div>
      </section>
    </Layout>
  );
}
