import type { EmailConfig } from "@/lib/email/config";
import { assertValidEmailAddress, sanitizeLongText, sanitizeText } from "@/lib/email/validation";
import { escapeHtml, renderButton, renderEmailLayout, textFooter } from "@/emails/components/layout";

export type EmailTemplateId =
  | "welcome"
  | "password_reset"
  | "email_verification"
  | "account_disabled"
  | "account_enabled"
  | "purchase_confirmation"
  | "access_granted"
  | "payment_failed"
  | "subscription_cancelled"
  | "contact_acknowledgement"
  | "contact_notification";

export type RenderedEmail = {
  subject: string;
  html: string;
  text: string;
  version: number;
};

export type EmailTemplateDefinition = {
  id: EmailTemplateId;
  version: number;
  enabled: boolean;
  render(data: Record<string, unknown>, config: EmailConfig): RenderedEmail;
};

function requireString(data: Record<string, unknown>, key: string, maxLength = 200) {
  const value = sanitizeText(data[key], maxLength);
  if (!value) throw new Error(`Missing required template field: ${key}`);
  return value;
}

function optionalString(data: Record<string, unknown>, key: string, maxLength = 200) {
  return sanitizeText(data[key], maxLength);
}

function appLink(config: EmailConfig, path: string) {
  return new URL(path, config.siteUrl).toString();
}

export const emailTemplates: Record<EmailTemplateId, EmailTemplateDefinition> = {
  welcome: {
    id: "welcome",
    version: 1,
    enabled: true,
    render(data, config) {
      const name = requireString(data, "name");
      const dashboardUrl = appLink(config, "/dashboard");
      const body = `
        <p style="margin:0 0 14px;">Hi ${escapeHtml(name)},</p>
        <p style="margin:0 0 14px;">Welcome to NursingMocks. Your account is ready, and you can start using your nursing exam practice resources now.</p>
        ${renderButton("Open Dashboard", dashboardUrl)}
        <p style="margin:0;">Use your dashboard to access practice resources, track progress, and continue your preparation.</p>
      `;
      return {
        subject: "Welcome to NursingMocks - Your account is ready",
        html: renderEmailLayout(config, "Welcome to NursingMocks", body),
        text: `Hi ${name},\n\nWelcome to NursingMocks. Your account is ready.\n\nOpen your dashboard: ${dashboardUrl}${textFooter(config)}`,
        version: 1,
      };
    },
  },
  password_reset: {
    id: "password_reset",
    version: 1,
    enabled: true,
    render(data, config) {
      const resetUrl = requireString(data, "resetUrl", 2000);
      const body = `
        <p style="margin:0 0 14px;">We received a request to reset your NursingMocks password.</p>
        <p style="margin:0 0 14px;">Use the secure link below to choose a new password.</p>
        ${renderButton("Reset Password", resetUrl)}
        <p style="margin:0 0 14px;">If you did not request this change, you can ignore this email. Your password will stay the same.</p>
        <p style="margin:0;color:#6b7280;font-size:13px;">For your security, this reset link can only be used through Firebase Authentication's password reset flow.</p>
      `;
      return {
        subject: "Reset your NursingMocks password",
        html: renderEmailLayout(config, "Reset your password", body),
        text: `Reset your NursingMocks password\n\nUse this secure link to choose a new password:\n${resetUrl}\n\nIf you did not request this change, you can ignore this email.${textFooter(config)}`,
        version: 1,
      };
    },
  },
  email_verification: {
    id: "email_verification",
    version: 1,
    enabled: true,
    render(data, config) {
      const verificationUrl = requireString(data, "verificationUrl", 2000);
      const body = `
        <p style="margin:0 0 14px;">Please verify your NursingMocks email address so your account stays secure.</p>
        <p style="margin:0 0 14px;">Use the secure link below to complete verification.</p>
        ${renderButton("Verify Email", verificationUrl)}
        <p style="margin:0 0 14px;">If you did not create a NursingMocks account, you can ignore this email.</p>
        <p style="margin:0;color:#6b7280;font-size:13px;">For your security, this verification link is generated by Firebase Authentication.</p>
      `;
      return {
        subject: "Verify your NursingMocks email",
        html: renderEmailLayout(config, "Verify your email", body),
        text: `Verify your NursingMocks email\n\nUse this secure link to verify your email address:\n${verificationUrl}\n\nIf you did not create a NursingMocks account, you can ignore this email.${textFooter(config)}`,
        version: 1,
      };
    },
  },
  account_disabled: {
    id: "account_disabled",
    version: 1,
    enabled: true,
    render(data, config) {
      const message = requireString(data, "message", 500);
      const supportUrl = appLink(config, "/contact");
      const body = `
        <p style="margin:0 0 14px;">Your NursingMocks account has been disabled by the support team.</p>
        <p style="margin:0 0 8px;"><strong>Reason:</strong></p>
        <p style="white-space:pre-wrap;margin:0 0 14px;">${escapeHtml(message)}</p>
        <p style="margin:0 0 14px;">If you believe this was a mistake, contact support so we can review your account.</p>
        ${renderButton("Contact Support", supportUrl)}
      `;
      return {
        subject: "Your NursingMocks account has been disabled",
        html: renderEmailLayout(config, "Account disabled", body),
        text: `Your NursingMocks account has been disabled by the support team.\n\nReason:\n${message}\n\nIf you believe this was a mistake, contact support: ${supportUrl}${textFooter(config)}`,
        version: 1,
      };
    },
  },
  account_enabled: {
    id: "account_enabled",
    version: 1,
    enabled: true,
    render(data, config) {
      const message = requireString(data, "message", 500);
      const loginUrl = appLink(config, "/login");
      const body = `
        <p style="margin:0 0 14px;">Your NursingMocks account has been enabled by the support team.</p>
        <p style="margin:0 0 8px;"><strong>Reason:</strong></p>
        <p style="white-space:pre-wrap;margin:0 0 14px;">${escapeHtml(message)}</p>
        <p style="margin:0 0 14px;">You can now sign in again and continue using your NursingMocks account.</p>
        ${renderButton("Sign In", loginUrl)}
      `;
      return {
        subject: "Your NursingMocks account has been enabled",
        html: renderEmailLayout(config, "Account enabled", body),
        text: `Your NursingMocks account has been enabled by the support team.\n\nReason:\n${message}\n\nYou can now sign in again: ${loginUrl}${textFooter(config)}`,
        version: 1,
      };
    },
  },
  contact_acknowledgement: {
    id: "contact_acknowledgement",
    version: 1,
    enabled: true,
    render(data, config) {
      const name = requireString(data, "name");
      const body = `
        <p style="margin:0 0 14px;">Hi ${escapeHtml(name)},</p>
        <p style="margin:0 0 14px;">We received your message and our support team will review it.</p>
        <p style="margin:0;">You can reply to this email if you need to add more context.</p>
      `;
      return {
        subject: "We received your NursingMocks message",
        html: renderEmailLayout(config, "We received your message", body),
        text: `Hi ${name},\n\nWe received your message and our support team will review it.${textFooter(config)}`,
        version: 1,
      };
    },
  },
  contact_notification: {
    id: "contact_notification",
    version: 1,
    enabled: true,
    render(data, config) {
      const name = requireString(data, "name");
      const email = requireString(data, "email");
      assertValidEmailAddress(email, "contact email");
      const topic = optionalString(data, "topic") || "General inquiry";
      const urgency = optionalString(data, "urgency") || "Not provided";
      const message = sanitizeLongText(data.message, 4000);
      if (!message) throw new Error("Missing required template field: message");
      const body = `
        <p style="margin:0 0 12px;"><strong>Name:</strong> ${escapeHtml(name)}</p>
        <p style="margin:0 0 12px;"><strong>Email:</strong> ${escapeHtml(email)}</p>
        <p style="margin:0 0 12px;"><strong>Topic:</strong> ${escapeHtml(topic)}</p>
        <p style="margin:0 0 12px;"><strong>Urgency:</strong> ${escapeHtml(urgency)}</p>
        <p style="margin:16px 0 6px;"><strong>Message:</strong></p>
        <p style="white-space:pre-wrap;margin:0;">${escapeHtml(message)}</p>
      `;
      return {
        subject: `Support request: ${topic}`,
        html: renderEmailLayout(config, "New support request", body),
        text: `New support request\n\nName: ${name}\nEmail: ${email}\nTopic: ${topic}\nUrgency: ${urgency}\n\n${message}`,
        version: 1,
      };
    },
  },
  purchase_confirmation: {
    id: "purchase_confirmation",
    version: 1,
    enabled: true,
    render(data, config) {
      const productName = requireString(data, "productName");
      const body = `<p>Your purchase for ${escapeHtml(productName)} was confirmed.</p>${renderButton("Open Dashboard", appLink(config, "/dashboard"))}`;
      return {
        subject: "Your NursingMocks purchase is confirmed",
        html: renderEmailLayout(config, "Purchase confirmed", body),
        text: `Your purchase for ${productName} was confirmed.${textFooter(config)}`,
        version: 1,
      };
    },
  },
  access_granted: {
    id: "access_granted",
    version: 1,
    enabled: true,
    render(data, config) {
      const accessName = requireString(data, "accessName");
      const body = `<p>Your access to ${escapeHtml(accessName)} is now active.</p>${renderButton("Start Practicing", appLink(config, "/dashboard"))}`;
      return {
        subject: "Your NursingMocks access is active",
        html: renderEmailLayout(config, "Access granted", body),
        text: `Your access to ${accessName} is now active.${textFooter(config)}`,
        version: 1,
      };
    },
  },
  payment_failed: {
    id: "payment_failed",
    version: 1,
    enabled: true,
    render(data, config) {
      const body = `<p>We could not process your latest payment. Please review your billing details or contact support.</p>`;
      return {
        subject: "NursingMocks payment issue",
        html: renderEmailLayout(config, "Payment issue", body),
        text: `We could not process your latest payment. Please review your billing details or contact support.${textFooter(config)}`,
        version: 1,
      };
    },
  },
  subscription_cancelled: {
    id: "subscription_cancelled",
    version: 1,
    enabled: true,
    render(data, config) {
      const body = `<p>Your NursingMocks subscription cancellation has been recorded. Contact support if this was unexpected.</p>`;
      return {
        subject: "NursingMocks subscription cancelled",
        html: renderEmailLayout(config, "Subscription cancelled", body),
        text: `Your NursingMocks subscription cancellation has been recorded.${textFooter(config)}`,
        version: 1,
      };
    },
  },
};

export function renderEmailTemplate(templateId: EmailTemplateId, data: Record<string, unknown>, config: EmailConfig) {
  const template = emailTemplates[templateId];
  if (!template) throw new Error(`Unknown email template: ${templateId}`);
  if (!template.enabled) throw new Error(`Email template is disabled: ${templateId}`);
  const rendered = template.render(data, config);
  if (data.__testEmail === true) {
    return {
      ...rendered,
      subject: `[TEST] ${rendered.subject}`,
    };
  }
  return rendered;
}

export function isEmailTemplateId(value: unknown): value is EmailTemplateId {
  return typeof value === "string" && value in emailTemplates;
}
